server:
  port: 8081
spring:
  application:
    name: eurekaclient
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true